package com.fuso.enterprise.ots.srv.api.service.functional;

import java.util.List;

import org.json.JSONException;
import org.json.JSONObject;

import com.fuso.enterprise.ots.srv.api.model.domain.OrderDetails;
import com.fuso.enterprise.ots.srv.api.model.domain.OrderProductDetails;
import com.fuso.enterprise.ots.srv.api.service.request.AddOrUpdateOrderProductBOrequest;
import com.fuso.enterprise.ots.srv.api.service.request.AddOrUpdateOrderTrackingRequest;
import com.fuso.enterprise.ots.srv.api.service.request.AddOrderPaymentDetailsRequest;
import com.fuso.enterprise.ots.srv.api.service.request.AddTransactionCancelRecordsRequest;
import com.fuso.enterprise.ots.srv.api.service.request.AssignOrderToEmployeeRequest;
import com.fuso.enterprise.ots.srv.api.service.request.CancelOrderRequest;
import com.fuso.enterprise.ots.srv.api.service.request.CloseEmployeeOrderRequest;
import com.fuso.enterprise.ots.srv.api.service.request.GetCustomerOrderByStatusBOrequest;
import com.fuso.enterprise.ots.srv.api.service.request.GetDistributorSettlementRequest;
import com.fuso.enterprise.ots.srv.api.service.request.GetListOfOrderByDateBORequest;
import com.fuso.enterprise.ots.srv.api.service.request.GetMonthlyDistributorSettlementRequest;
import com.fuso.enterprise.ots.srv.api.service.request.GetOrderBORequest;
import com.fuso.enterprise.ots.srv.api.service.request.GetOrderByOrderIdAndStatusRequest;
import com.fuso.enterprise.ots.srv.api.service.request.GetOrderByStatusRequest;
import com.fuso.enterprise.ots.srv.api.service.request.GetRRCOrdersByStatusRequest;
import com.fuso.enterprise.ots.srv.api.service.request.InsertOrderRequest;
import com.fuso.enterprise.ots.srv.api.service.request.UpdateOrderDetailsRequest;
import com.fuso.enterprise.ots.srv.api.service.request.UpdateOrderProductStatusRequest;
import com.fuso.enterprise.ots.srv.api.service.request.UpdateRRCStatusRequest;
import com.fuso.enterprise.ots.srv.api.service.response.CcAvenueOrderDetailsResponse;
import com.fuso.enterprise.ots.srv.api.service.response.GetDistributorSettlementResponse;
import com.fuso.enterprise.ots.srv.api.service.response.GetListOfOrderByDateBOResponse;
import com.fuso.enterprise.ots.srv.api.service.response.OrderDetailsBOResponse;
import com.fuso.enterprise.ots.srv.api.service.response.OrderProductAndOrderResponse;
import com.fuso.enterprise.ots.srv.api.service.response.OrderProductBOResponse;

public interface OTSOrderService {
	OrderDetailsBOResponse getOrderBydate(GetOrderBORequest getOrderBORequest);
	OrderProductBOResponse getOrderByStatusAndDistributor(GetOrderByStatusRequest getOrderByStatusRequest);
	OrderProductBOResponse insertOrderAndProduct(AddOrUpdateOrderProductBOrequest addOrUpdateOrderProductBOrequest);
	OrderProductBOResponse getCustomerOrderStatus(GetCustomerOrderByStatusBOrequest getCustomerOrderByStatusBOrequest);
	OrderProductBOResponse getOrderDetailsByDate(GetOrderBORequest getOrderBORequest);
	GetListOfOrderByDateBOResponse getListOfOrderByDate(GetListOfOrderByDateBORequest getListOfOrderByDateBORequest);
	OrderProductBOResponse orderReportByDate(GetOrderBORequest getOrderBORequest);
	String schedulerOrder(AddOrUpdateOrderProductBOrequest addOrUpdateOrderProductBOrequest);
	OrderDetailsBOResponse getRazorPayOrder(UpdateOrderDetailsRequest updateOrderDetailsRequest) throws JSONException;
	JSONObject fetchPaymentDetailsByPaymetId(String paymentId);
	OrderProductBOResponse getOrderDetailsForOrderId(String OrderId);
	String closeMainOrder(String OrderId);
	String closeEmployeeOrder(CloseEmployeeOrderRequest  closeEmployeeOrderRequest);
	String assignOrderToEmployee(AssignOrderToEmployeeRequest assignOrderToEmployeeRequest);
	boolean checkForOrderAssigned(String orderId);
	String cancelMainOrder(String orderId, String orderCancelReason, String orderCancelledBy);
	String cancelSubOrder(String orderId, String productId, String orderCancelReason, String orderCancelledBy);
	String cancelMainAndSubOrder(CancelOrderRequest cancelOrderRequest);
	boolean checkForOrderCancel(String orderId);
	List<String> getNewSubordersBeforeCurrentDate();
	String autoCancelOrderByDistributor();
	CcAvenueOrderDetailsResponse getCCAvenueCredentials();
	OrderDetails addPaymentDetailsForOrder(AddOrderPaymentDetailsRequest addOrderPaymentDetailsRequest);
	List<List<String>> getOrderDetailsForInvoice(String orderId);
	List<List<String>> getDistributorForOrderInvoice(String orderId);
	OrderProductBOResponse getOrdersByStatus(String orderStatus);
	List<OrderProductDetails> getOrderByStatusOfUnregisteredDistributors(String subOrderStatus);
	String updateRRCOrderStatus(UpdateRRCStatusRequest updateRRCStatusRequest);
	boolean checkForOrderClosed(String orderId);
	GetDistributorSettlementResponse getDistributorWeeklySettlemetDetails(GetDistributorSettlementRequest getDistributorSettlementRequest);
	GetDistributorSettlementResponse getDistributorCurrentWeekSettlemetDetails(String distributorId);
	GetDistributorSettlementResponse getDistributorMonthlySettlemetDetails(GetMonthlyDistributorSettlementRequest getDistributorSettlementRequest);
	OrderProductAndOrderResponse getCancelledOrdersByDistributor(String distributorId);
	OrderProductAndOrderResponse getReturnReplacementOrdersForDistributor(String distributorId);
	OrderProductAndOrderResponse getRRCOrdersByDistributor(GetRRCOrdersByStatusRequest getRRCOrdersByStatusRequest);
	OrderProductAndOrderResponse getRRClosedOrdersByDistributor(String distributorId);
	OrderProductAndOrderResponse getOrderByDistributorIdAndSubOrderStatus(GetOrderByStatusRequest getOrderByStatusRequest);
	String addPaymentTransactionCancelRecords(AddTransactionCancelRecordsRequest addPaymentTransactionCancelRecords);
	String generateDeliveryNote(String orderId);
	List<OrderProductDetails> getSubOrderDetailsByOrderProductId(String orderProductId);
	OrderProductBOResponse getRRCOrdersByCustomer(GetCustomerOrderByStatusBOrequest getCustomerOrderByStatusBOrequest);
	OrderProductBOResponse getCustomerOrderByOrderProductStatus(GetCustomerOrderByStatusBOrequest getCustomerOrderByStatusBOrequest);
	OrderProductBOResponse getOrderByOrderIdOrderProductStatus(GetOrderByOrderIdAndStatusRequest getOrderByOrderIdAndStatusRequest);
	OrderProductBOResponse getOrderByOrderIdRRCOrderStatus(GetOrderByOrderIdAndStatusRequest getOrderByOrderIdAndStatusRequest);
	OrderProductBOResponse insertOrder(InsertOrderRequest insertOrderRequest);
	List<OrderDetails> getOrderByOrderTransactionId(String otsTransactionCancelOrderId);
	List<List<String>> getOrderProductDetailsForInvoice(String orderId, String productId);
	List<List<String>> getDistributorForOrderProductInvoice(String orderId, String productId);
	String generateOrderProductInvoicePdf(String orderId, String productId);
	String addOrUpdateOrderTracking(AddOrUpdateOrderTrackingRequest addOrUpdateOrderTrackingRequest);
	OrderProductDetails getOrderProductByOrderIdProductId(String orderId, String productId);
	List<OrderProductDetails> checkPendingOrdersOfInactiveDistributor(String distributorId);
	String updateOrderProductStatus(UpdateOrderProductStatusRequest updateOrderProductStatusRequest);
	List<String> getPaymentPendingOrdersBeforeCurrentDate();
	String autoCancelOrderByCustomer();
	List<List<String>> getDistributorPaymentDetailsForProformaInvoice(String distributorId);
	List<List<String>> getOrderDetailsForProformaInvoice(String orderId);
	String generateProformaOrderInvoicePdf(String orderId, String distributorId);
	
	
}
